# Generated by Django 2.2.7 on 2020-10-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookUser',
        ),
    ]
